"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
format = "$character"
right_format = "$python$directory$git_branch$git_state$git_status"

[character]
format = "$symbol "
success_symbol = "[❯](bold #7aa2f7)"
error_symbol = "[❯](bold #f7768e)"
vimcmd_symbol = "[❮](bold #9ece6a)"
vimcmd_visual_symbol = "[❮](bold #e0af68)"
vimcmd_replace_symbol = "[❮](bold #bb9af7)"
vimcmd_replace_one_symbol = "[❮](bold #bb9af7)"

[python]
format = "[ $virtualenv](#e0af68)  "
detect_extensions = []
detect_files = []

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"
style = "#7aa2f7"
repo_root_style = "bold #7aa2f7"
read_only = " 󰌾"
read_only_style = "#f7768e"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = "  [$symbol$branch]($style)"
style = "bold #bb9af7"
truncation_length = 24
truncation_symbol = "…"

[git_state]
format = "  [$state( $progress_current/$progress_total)]($style)"
style = "bold #ff9e64"

[git_status]
format = " $all_status$ahead_behind"
conflicted = "[=](bold #f7768e)"
ahead = "[⇡${count}](bold #9ece6a)"
behind = "[⇣${count}](bold #f7768e)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](bold #ff9e64)"
untracked = "[?](bold #e0af68)"
stashed = "[≡](bold #bb9af7)"
modified = "[!](bold #e0af68)"
staged = "[+](bold #9ece6a)"
renamed = "[»](bold #7dcfff)"
deleted = "[✘](bold #f7768e)"
